name: scan-actions

on:
#    schedule:
#      - cron: '0 0 * * *'
# Remove both comments to run this action on daily basis.
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: xray tools
 
        run: |
          wget https://github.com/chaitin/xray/releases/download/1.9.3/xray_linux_amd64.zip
          #https://github.com/chaitin/xray/releases/download/1.9.3/xray_linux_arm64.zip
          pwd
          unzip xray_linux_amd64.zip
          ls -al
          ./xray_linux_amd64 webscan
          ./xray_linux_amd64 webscan --url http://testphp.vulnweb.com/
          
        shell: bash
